import "./globals.css";
import type { Metadata } from "next";
import { Particles } from "@/components/magicui/particles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-screen">
      <body className="font-['Plus_Jakarta_Sans',sans-serif] antialiased bg-[var(--main-bg)] min-h-screen relative overflow-hidden">
        {children}
        <Particles
          className="absolute inset-0 z-0"
          quantity={200}
          ease={80}
          color="#ffffffd0"
          refresh
        />
      </body>
    </html>
  );
}
